name: Debug

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Build_Linux_Windows:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc-multilib
          sudo apt-get install -y gcc-mingw-w64

      - name: Build Linux AMD64
        run: |
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_linux_amd64_pr_$SHORT_COMMIT_ID
          else
            FILENAME=ledu_download_linux_amd64_$SHORT_COMMIT_ID
          fi
          fyne package --target linux --name $FILENAME
          upx --best $FILENAME

      - name: Build Windows
        env:
          CGO_ENABLED: 1
          CC: x86_64-w64-mingw32-gcc
          GOOS: windows
          GOARCH: amd64
        run: |
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_win64_PR_$SHORT_COMMIT_ID.exe
          else
            FILENAME=ledu_download_win64_$SHORT_COMMIT_ID.exe
          fi
          fyne package --target windows --name $FILENAME
          upx --best $FILENAME

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Linux-Windows-build"
          path: |
            ledu_download_linux_amd64_*
            ledu_download_win64_*.exe

  Build_MacOS_ARM64_Android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install UPX
        run: brew install upx

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2

      - name: Set Android Environment Variables
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV

      - name: Build macOS ARM64
        run: |
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_macos_arm64_pr_$SHORT_COMMIT_ID
          else
            FILENAME=ledu_download_macos_arm64_$SHORT_COMMIT_ID
          fi
          fyne package --target darwin --name $FILENAME.app
          upx --best $FILENAME.app/Contents/MacOS/* || true
          zip -r -X $FILENAME.zip $FILENAME.app

      - name: Build Android ARM64
        run: |
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_android_arm64_pr_$SHORT_COMMIT_ID.apk
          else
            FILENAME=ledu_download_android_arm64_$SHORT_COMMIT_ID.apk
          fi
          fyne package --target android/arm64 --name $FILENAME

      - name: Build Android ARM
        run: |
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_android_arm_pr_$SHORT_COMMIT_ID.apk
          else
            FILENAME=ledu_download_android_arm_$SHORT_COMMIT_ID.apk
          fi
          fyne package --target android/arm --name $FILENAME

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS-ARM64-Android-build"
          path: |
            ledu_download_macos_arm64_*.zip
            ledu_download_android_arm64_*.apk
            ledu_download_android_arm_*.apk

  Build_MacOS_Intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install UPX
        run: brew install upx

      - name: Build macOS x86_64
        run: |
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_macos_x86_64_pr_$SHORT_COMMIT_ID
          else
            FILENAME=ledu_download_macos_x86_64_$SHORT_COMMIT_ID
          fi
          fyne package --target darwin --name $FILENAME.app
          upx --best $FILENAME.app/Contents/MacOS/* || true
          zip -r -X $FILENAME.zip $FILENAME.app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS-x86_64-build"
          path: ledu_download_macos_x86_64_*.zip